comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  hide_project_coverage: false # set to false
  require_changes: false
  require_base: false        # [true :: must have a base report to post]
  require_head: true         # [true :: must have a head report to post]
codecov:
  branch: develop
coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      mca:  # declare a new status context "mca"
        target: 75%
        threshold: 5%
        paths: 
          - "src/"
      test:
        target: 100%
        threshold: 5%
        paths:
          - "test/"
